[build]
builder = "nixpacks"
buildCommand = "npm install --no-package-lock && cd backend && npm install --no-package-lock && cd ../frontend && npm install --no-package-lock"

[deploy]
startCommand = "cd backend && node server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100 