[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install && cd ../frontend && npm install"

[deploy]
startCommand = "cd backend && node server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100 