[build]
builder = "nixpacks"
buildCommand = "chmod +x build.sh && ./build.sh"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "on-failure" 