[build]
builder = "nixpacks"
buildCommand = "npm install && cd backend && npm install && cd ../frontend && npm install"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "on-failure" 